# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: note-taking
# spec:
#   destination:
#     name: ''
#     namespace: default
#     server: 'https://kubernetes.default.svc'
#   source:
#     path: k8s
#     repoURL: 'https://github.com/sirlegendary/note-taking.git'
#     targetRevision: HEAD
#   project: default
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
