image:
  pullPolicy: IfNotPresent
  repository: 814560518754.dkr.ecr.us-east-1.amazonaws.com
  version: 3ce3554a7d3daf8a94c72f71fd1cffe594612b3c

# user: custom-value
# password: custom-value
# host: custom-value
# name: custom-value
# access_key: custom-value
# secret_key: custom-value
# bucket: custom-value
