image:
  pullPolicy: IfNotPresent
  repository: 689418509725.dkr.ecr.us-east-1.amazonaws.com/my-cool-application
  version: d9be9d02df87c846054c8e32c5c12f7f4af387e3

# user: custom-value
# password: custom-value
# host: custom-value
# name: custom-value
# access_key: custom-value
# secret_key: custom-value
# bucket: custom-value