image:
  pullPolicy: IfNotPresent
  repository: 814560518754.dkr.ecr.us-east-1.amazonaws.com/my-cool-application
  version: 93b43d7943fa3de735dba217431bb335eb5e2add

# user: custom-value
# password: custom-value
# host: custom-value
# name: custom-value
# access_key: custom-value
# secret_key: custom-value
# bucket: custom-value
