apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    domain: app
spec:
  replicas: 5
  selector:
    matchLabels:
      domain: app
  template:
    metadata:
      name: app-template
      labels:
        domain: app
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: appsecrets
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: name
                  name: appsecrets
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: appsecrets
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DJANGO_AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: aws_access_key
                  name: appsecrets
            - name: DJANGO_AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: aws_secret_key
                  name: appsecrets
            - name: DJANGO_AWS_STORAGE_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  key: bucket
                  name: appsecrets
            - name: DJANGO_ACCOUNT_ALLOW_REGISTRATION
              value: "True"
            - name: DJANGO_ALLOWED_HOSTS
              value: ".amazonaws.com"
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: django_secret_key
                  name: appsecrets
            - name: DJANGO_ADMIN_URL
              valueFrom:
                secretKeyRef:
                  key: django_admin_url
                  name: appsecrets
          ports:
            - containerPort: 8000
